/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot.impl;

import com.raptor.mcloottable.mcloot.EnchantRandomlyLootFunction;
import com.raptor.mcloottable.mcloot.MclootPackage;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enchant Randomly Loot Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcloottable.mcloot.impl.EnchantRandomlyLootFunctionImpl#getEnchantments <em>Enchantments</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnchantRandomlyLootFunctionImpl extends LootFunctionImpl implements EnchantRandomlyLootFunction
{
  /**
   * The cached value of the '{@link #getEnchantments() <em>Enchantments</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnchantments()
   * @generated
   * @ordered
   */
  protected EList<String> enchantments;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnchantRandomlyLootFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MclootPackage.Literals.ENCHANT_RANDOMLY_LOOT_FUNCTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getEnchantments()
  {
    if (enchantments == null)
    {
      enchantments = new EDataTypeEList<String>(String.class, this, MclootPackage.ENCHANT_RANDOMLY_LOOT_FUNCTION__ENCHANTMENTS);
    }
    return enchantments;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MclootPackage.ENCHANT_RANDOMLY_LOOT_FUNCTION__ENCHANTMENTS:
        return getEnchantments();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MclootPackage.ENCHANT_RANDOMLY_LOOT_FUNCTION__ENCHANTMENTS:
        getEnchantments().clear();
        getEnchantments().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MclootPackage.ENCHANT_RANDOMLY_LOOT_FUNCTION__ENCHANTMENTS:
        getEnchantments().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MclootPackage.ENCHANT_RANDOMLY_LOOT_FUNCTION__ENCHANTMENTS:
        return enchantments != null && !enchantments.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (enchantments: ");
    result.append(enchantments);
    result.append(')');
    return result.toString();
  }

} //EnchantRandomlyLootFunctionImpl
