/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot.impl;

import com.raptor.mcloottable.mcloot.MCJsonNumber;
import com.raptor.mcloottable.mcloot.MclootPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>MC Json Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MCJsonNumberImpl extends MCJsonValueImpl implements MCJsonNumber
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MCJsonNumberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MclootPackage.Literals.MC_JSON_NUMBER;
  }

} //MCJsonNumberImpl
