/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot.impl;

import com.raptor.mcloottable.mcloot.MclootPackage;
import com.raptor.mcloottable.mcloot.RecipePredicate;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Recipe Predicate</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcloottable.mcloot.impl.RecipePredicateImpl#getRecipe <em>Recipe</em>}</li>
 *   <li>{@link com.raptor.mcloottable.mcloot.impl.RecipePredicateImpl#isDidNotGet <em>Did Not Get</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RecipePredicateImpl extends MinimalEObjectImpl.Container implements RecipePredicate
{
  /**
   * The default value of the '{@link #getRecipe() <em>Recipe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecipe()
   * @generated
   * @ordered
   */
  protected static final String RECIPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRecipe() <em>Recipe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecipe()
   * @generated
   * @ordered
   */
  protected String recipe = RECIPE_EDEFAULT;

  /**
   * The default value of the '{@link #isDidNotGet() <em>Did Not Get</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isDidNotGet()
   * @generated
   * @ordered
   */
  protected static final boolean DID_NOT_GET_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isDidNotGet() <em>Did Not Get</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isDidNotGet()
   * @generated
   * @ordered
   */
  protected boolean didNotGet = DID_NOT_GET_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RecipePredicateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MclootPackage.Literals.RECIPE_PREDICATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRecipe()
  {
    return recipe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRecipe(String newRecipe)
  {
    String oldRecipe = recipe;
    recipe = newRecipe;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclootPackage.RECIPE_PREDICATE__RECIPE, oldRecipe, recipe));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isDidNotGet()
  {
    return didNotGet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDidNotGet(boolean newDidNotGet)
  {
    boolean oldDidNotGet = didNotGet;
    didNotGet = newDidNotGet;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclootPackage.RECIPE_PREDICATE__DID_NOT_GET, oldDidNotGet, didNotGet));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MclootPackage.RECIPE_PREDICATE__RECIPE:
        return getRecipe();
      case MclootPackage.RECIPE_PREDICATE__DID_NOT_GET:
        return isDidNotGet();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MclootPackage.RECIPE_PREDICATE__RECIPE:
        setRecipe((String)newValue);
        return;
      case MclootPackage.RECIPE_PREDICATE__DID_NOT_GET:
        setDidNotGet((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MclootPackage.RECIPE_PREDICATE__RECIPE:
        setRecipe(RECIPE_EDEFAULT);
        return;
      case MclootPackage.RECIPE_PREDICATE__DID_NOT_GET:
        setDidNotGet(DID_NOT_GET_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MclootPackage.RECIPE_PREDICATE__RECIPE:
        return RECIPE_EDEFAULT == null ? recipe != null : !RECIPE_EDEFAULT.equals(recipe);
      case MclootPackage.RECIPE_PREDICATE__DID_NOT_GET:
        return didNotGet != DID_NOT_GET_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (recipe: ");
    result.append(recipe);
    result.append(", didNotGet: ");
    result.append(didNotGet);
    result.append(')');
    return result.toString();
  }

} //RecipePredicateImpl
