/*
 * generated by Xtext 2.21.0
 */
package com.raptor.mcblockstate


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class McblockstateStandaloneSetup extends McblockstateStandaloneSetupGenerated {

	def static void doSetup() {
		new McblockstateStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
