/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcmodel.mcmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Display</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Display#getThirdperson_righthand <em>Thirdperson righthand</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Display#getThirdperson_lefthand <em>Thirdperson lefthand</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Display#getFirstperson_righthand <em>Firstperson righthand</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Display#getFirstperson_lefthand <em>Firstperson lefthand</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Display#getGui <em>Gui</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Display#getHead <em>Head</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Display#getGround <em>Ground</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Display#getFixed <em>Fixed</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay()
 * @model
 * @generated
 */
public interface Display extends EObject
{
  /**
   * Returns the value of the '<em><b>Thirdperson righthand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thirdperson righthand</em>' containment reference.
   * @see #setThirdperson_righthand(Morph)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay_Thirdperson_righthand()
   * @model containment="true"
   * @generated
   */
  Morph getThirdperson_righthand();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Display#getThirdperson_righthand <em>Thirdperson righthand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thirdperson righthand</em>' containment reference.
   * @see #getThirdperson_righthand()
   * @generated
   */
  void setThirdperson_righthand(Morph value);

  /**
   * Returns the value of the '<em><b>Thirdperson lefthand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thirdperson lefthand</em>' containment reference.
   * @see #setThirdperson_lefthand(Morph)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay_Thirdperson_lefthand()
   * @model containment="true"
   * @generated
   */
  Morph getThirdperson_lefthand();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Display#getThirdperson_lefthand <em>Thirdperson lefthand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thirdperson lefthand</em>' containment reference.
   * @see #getThirdperson_lefthand()
   * @generated
   */
  void setThirdperson_lefthand(Morph value);

  /**
   * Returns the value of the '<em><b>Firstperson righthand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Firstperson righthand</em>' containment reference.
   * @see #setFirstperson_righthand(Morph)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay_Firstperson_righthand()
   * @model containment="true"
   * @generated
   */
  Morph getFirstperson_righthand();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Display#getFirstperson_righthand <em>Firstperson righthand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Firstperson righthand</em>' containment reference.
   * @see #getFirstperson_righthand()
   * @generated
   */
  void setFirstperson_righthand(Morph value);

  /**
   * Returns the value of the '<em><b>Firstperson lefthand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Firstperson lefthand</em>' containment reference.
   * @see #setFirstperson_lefthand(Morph)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay_Firstperson_lefthand()
   * @model containment="true"
   * @generated
   */
  Morph getFirstperson_lefthand();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Display#getFirstperson_lefthand <em>Firstperson lefthand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Firstperson lefthand</em>' containment reference.
   * @see #getFirstperson_lefthand()
   * @generated
   */
  void setFirstperson_lefthand(Morph value);

  /**
   * Returns the value of the '<em><b>Gui</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gui</em>' containment reference.
   * @see #setGui(Morph)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay_Gui()
   * @model containment="true"
   * @generated
   */
  Morph getGui();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Display#getGui <em>Gui</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gui</em>' containment reference.
   * @see #getGui()
   * @generated
   */
  void setGui(Morph value);

  /**
   * Returns the value of the '<em><b>Head</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Head</em>' containment reference.
   * @see #setHead(Morph)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay_Head()
   * @model containment="true"
   * @generated
   */
  Morph getHead();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Display#getHead <em>Head</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Head</em>' containment reference.
   * @see #getHead()
   * @generated
   */
  void setHead(Morph value);

  /**
   * Returns the value of the '<em><b>Ground</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ground</em>' containment reference.
   * @see #setGround(Morph)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay_Ground()
   * @model containment="true"
   * @generated
   */
  Morph getGround();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Display#getGround <em>Ground</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ground</em>' containment reference.
   * @see #getGround()
   * @generated
   */
  void setGround(Morph value);

  /**
   * Returns the value of the '<em><b>Fixed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fixed</em>' containment reference.
   * @see #setFixed(Morph)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getDisplay_Fixed()
   * @model containment="true"
   * @generated
   */
  Morph getFixed();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Display#getFixed <em>Fixed</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fixed</em>' containment reference.
   * @see #getFixed()
   * @generated
   */
  void setFixed(Morph value);

} // Display
