/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcmodel.mcmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vec4d</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Vec4d#getX1 <em>X1</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Vec4d#getY1 <em>Y1</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Vec4d#getX2 <em>X2</em>}</li>
 *   <li>{@link com.raptor.mcmodel.mcmodel.Vec4d#getY2 <em>Y2</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getVec4d()
 * @model
 * @generated
 */
public interface Vec4d extends EObject
{
  /**
   * Returns the value of the '<em><b>X1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X1</em>' attribute.
   * @see #setX1(double)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getVec4d_X1()
   * @model
   * @generated
   */
  double getX1();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Vec4d#getX1 <em>X1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X1</em>' attribute.
   * @see #getX1()
   * @generated
   */
  void setX1(double value);

  /**
   * Returns the value of the '<em><b>Y1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y1</em>' attribute.
   * @see #setY1(double)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getVec4d_Y1()
   * @model
   * @generated
   */
  double getY1();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Vec4d#getY1 <em>Y1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y1</em>' attribute.
   * @see #getY1()
   * @generated
   */
  void setY1(double value);

  /**
   * Returns the value of the '<em><b>X2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X2</em>' attribute.
   * @see #setX2(double)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getVec4d_X2()
   * @model
   * @generated
   */
  double getX2();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Vec4d#getX2 <em>X2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X2</em>' attribute.
   * @see #getX2()
   * @generated
   */
  void setX2(double value);

  /**
   * Returns the value of the '<em><b>Y2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y2</em>' attribute.
   * @see #setY2(double)
   * @see com.raptor.mcmodel.mcmodel.McmodelPackage#getVec4d_Y2()
   * @model
   * @generated
   */
  double getY2();

  /**
   * Sets the value of the '{@link com.raptor.mcmodel.mcmodel.Vec4d#getY2 <em>Y2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y2</em>' attribute.
   * @see #getY2()
   * @generated
   */
  void setY2(double value);

} // Vec4d
