/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Properties Loot Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcloottable.mcloot.EntityPropertiesLootCondition#getEntity <em>Entity</em>}</li>
 *   <li>{@link com.raptor.mcloottable.mcloot.EntityPropertiesLootCondition#getPredicate <em>Predicate</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcloottable.mcloot.MclootPackage#getEntityPropertiesLootCondition()
 * @model
 * @generated
 */
public interface EntityPropertiesLootCondition extends NamedLootCondition
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' attribute.
   * The literals are from the enumeration {@link com.raptor.mcloottable.mcloot.EnumEntitySource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' attribute.
   * @see com.raptor.mcloottable.mcloot.EnumEntitySource
   * @see #setEntity(EnumEntitySource)
   * @see com.raptor.mcloottable.mcloot.MclootPackage#getEntityPropertiesLootCondition_Entity()
   * @model
   * @generated
   */
  EnumEntitySource getEntity();

  /**
   * Sets the value of the '{@link com.raptor.mcloottable.mcloot.EntityPropertiesLootCondition#getEntity <em>Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' attribute.
   * @see com.raptor.mcloottable.mcloot.EnumEntitySource
   * @see #getEntity()
   * @generated
   */
  void setEntity(EnumEntitySource value);

  /**
   * Returns the value of the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' containment reference.
   * @see #setPredicate(EntityPredicate)
   * @see com.raptor.mcloottable.mcloot.MclootPackage#getEntityPropertiesLootCondition_Predicate()
   * @model containment="true"
   * @generated
   */
  EntityPredicate getPredicate();

  /**
   * Sets the value of the '{@link com.raptor.mcloottable.mcloot.EntityPropertiesLootCondition#getPredicate <em>Predicate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' containment reference.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(EntityPredicate value);

} // EntityPropertiesLootCondition
