/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Enum NBT Source</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.raptor.mcloottable.mcloot.MclootPackage#getEnumNBTSource()
 * @model
 * @generated
 */
public enum EnumNBTSource implements Enumerator
{
  /**
   * The '<em><b>BLOCK ENTITY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLOCK_ENTITY_VALUE
   * @generated
   * @ordered
   */
  BLOCK_ENTITY(0, "BLOCK_ENTITY", "block_entity"),

  /**
   * The '<em><b>THIS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THIS_VALUE
   * @generated
   * @ordered
   */
  THIS(1, "THIS", "this"),

  /**
   * The '<em><b>KILLER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KILLER_VALUE
   * @generated
   * @ordered
   */
  KILLER(2, "KILLER", "killer"),

  /**
   * The '<em><b>KILLER PLAYER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KILLER_PLAYER_VALUE
   * @generated
   * @ordered
   */
  KILLER_PLAYER(3, "KILLER_PLAYER", "killer_player");

  /**
   * The '<em><b>BLOCK ENTITY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLOCK_ENTITY
   * @model literal="block_entity"
   * @generated
   * @ordered
   */
  public static final int BLOCK_ENTITY_VALUE = 0;

  /**
   * The '<em><b>THIS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THIS
   * @model literal="this"
   * @generated
   * @ordered
   */
  public static final int THIS_VALUE = 1;

  /**
   * The '<em><b>KILLER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KILLER
   * @model literal="killer"
   * @generated
   * @ordered
   */
  public static final int KILLER_VALUE = 2;

  /**
   * The '<em><b>KILLER PLAYER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KILLER_PLAYER
   * @model literal="killer_player"
   * @generated
   * @ordered
   */
  public static final int KILLER_PLAYER_VALUE = 3;

  /**
   * An array of all the '<em><b>Enum NBT Source</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final EnumNBTSource[] VALUES_ARRAY =
    new EnumNBTSource[]
    {
      BLOCK_ENTITY,
      THIS,
      KILLER,
      KILLER_PLAYER,
    };

  /**
   * A public read-only list of all the '<em><b>Enum NBT Source</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<EnumNBTSource> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Enum NBT Source</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static EnumNBTSource get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      EnumNBTSource result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Enum NBT Source</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static EnumNBTSource getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      EnumNBTSource result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Enum NBT Source</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static EnumNBTSource get(int value)
  {
    switch (value)
    {
      case BLOCK_ENTITY_VALUE: return BLOCK_ENTITY;
      case THIS_VALUE: return THIS;
      case KILLER_VALUE: return KILLER;
      case KILLER_PLAYER_VALUE: return KILLER_PLAYER;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EnumNBTSource(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //EnumNBTSource
