/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loot Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.raptor.mcloottable.mcloot.MclootPackage#getLootCondition()
 * @model
 * @generated
 */
public interface LootCondition extends EObject
{
} // LootCondition
