/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.raptor.mcloottable.mcloot.MclootPackage
 * @generated
 */
public interface MclootFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MclootFactory eINSTANCE = com.raptor.mcloottable.mcloot.impl.MclootFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Loot Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loot Table</em>'.
   * @generated
   */
  LootTable createLootTable();

  /**
   * Returns a new object of class '<em>Loot Pool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loot Pool</em>'.
   * @generated
   */
  LootPool createLootPool();

  /**
   * Returns a new object of class '<em>Loot Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loot Entry</em>'.
   * @generated
   */
  LootEntry createLootEntry();

  /**
   * Returns a new object of class '<em>Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loot Function</em>'.
   * @generated
   */
  LootFunction createLootFunction();

  /**
   * Returns a new object of class '<em>Apply Bonus Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Apply Bonus Loot Function</em>'.
   * @generated
   */
  ApplyBonusLootFunction createApplyBonusLootFunction();

  /**
   * Returns a new object of class '<em>Copy Name Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Copy Name Loot Function</em>'.
   * @generated
   */
  CopyNameLootFunction createCopyNameLootFunction();

  /**
   * Returns a new object of class '<em>Copy NBT Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Copy NBT Loot Function</em>'.
   * @generated
   */
  CopyNBTLootFunction createCopyNBTLootFunction();

  /**
   * Returns a new object of class '<em>NBT Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NBT Operation</em>'.
   * @generated
   */
  NBTOperation createNBTOperation();

  /**
   * Returns a new object of class '<em>Append NBT Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Append NBT Operation</em>'.
   * @generated
   */
  AppendNBTOperation createAppendNBTOperation();

  /**
   * Returns a new object of class '<em>Replace NBT Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Replace NBT Operation</em>'.
   * @generated
   */
  ReplaceNBTOperation createReplaceNBTOperation();

  /**
   * Returns a new object of class '<em>Merge NBT Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Merge NBT Operation</em>'.
   * @generated
   */
  MergeNBTOperation createMergeNBTOperation();

  /**
   * Returns a new object of class '<em>Copy State Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Copy State Loot Function</em>'.
   * @generated
   */
  CopyStateLootFunction createCopyStateLootFunction();

  /**
   * Returns a new object of class '<em>Enchant Randomly Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enchant Randomly Loot Function</em>'.
   * @generated
   */
  EnchantRandomlyLootFunction createEnchantRandomlyLootFunction();

  /**
   * Returns a new object of class '<em>Enchant With Levels Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enchant With Levels Loot Function</em>'.
   * @generated
   */
  EnchantWithLevelsLootFunction createEnchantWithLevelsLootFunction();

  /**
   * Returns a new object of class '<em>Exploration Map Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exploration Map Loot Function</em>'.
   * @generated
   */
  ExplorationMapLootFunction createExplorationMapLootFunction();

  /**
   * Returns a new object of class '<em>Explosion Decay Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Explosion Decay Loot Function</em>'.
   * @generated
   */
  ExplosionDecayLootFunction createExplosionDecayLootFunction();

  /**
   * Returns a new object of class '<em>Furnace Smelt Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Furnace Smelt Loot Function</em>'.
   * @generated
   */
  FurnaceSmeltLootFunction createFurnaceSmeltLootFunction();

  /**
   * Returns a new object of class '<em>Fill Player Head Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fill Player Head Loot Function</em>'.
   * @generated
   */
  FillPlayerHeadLootFunction createFillPlayerHeadLootFunction();

  /**
   * Returns a new object of class '<em>Limit Count Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Limit Count Loot Function</em>'.
   * @generated
   */
  LimitCountLootFunction createLimitCountLootFunction();

  /**
   * Returns a new object of class '<em>Looting Enchant Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Looting Enchant Loot Function</em>'.
   * @generated
   */
  LootingEnchantLootFunction createLootingEnchantLootFunction();

  /**
   * Returns a new object of class '<em>Set Attributes Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Attributes Loot Function</em>'.
   * @generated
   */
  SetAttributesLootFunction createSetAttributesLootFunction();

  /**
   * Returns a new object of class '<em>Attribute Modifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Modifier</em>'.
   * @generated
   */
  AttributeModifier createAttributeModifier();

  /**
   * Returns a new object of class '<em>Set Contents Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Contents Loot Function</em>'.
   * @generated
   */
  SetContentsLootFunction createSetContentsLootFunction();

  /**
   * Returns a new object of class '<em>Set Count Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Count Loot Function</em>'.
   * @generated
   */
  SetCountLootFunction createSetCountLootFunction();

  /**
   * Returns a new object of class '<em>Count</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Count</em>'.
   * @generated
   */
  Count createCount();

  /**
   * Returns a new object of class '<em>Exact Count</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exact Count</em>'.
   * @generated
   */
  ExactCount createExactCount();

  /**
   * Returns a new object of class '<em>Special Count</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Special Count</em>'.
   * @generated
   */
  SpecialCount createSpecialCount();

  /**
   * Returns a new object of class '<em>Uniform Count</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uniform Count</em>'.
   * @generated
   */
  UniformCount createUniformCount();

  /**
   * Returns a new object of class '<em>Binomial Count</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Binomial Count</em>'.
   * @generated
   */
  BinomialCount createBinomialCount();

  /**
   * Returns a new object of class '<em>Set Damage Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Damage Loot Function</em>'.
   * @generated
   */
  SetDamageLootFunction createSetDamageLootFunction();

  /**
   * Returns a new object of class '<em>Set Lore Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Lore Loot Function</em>'.
   * @generated
   */
  SetLoreLootFunction createSetLoreLootFunction();

  /**
   * Returns a new object of class '<em>Set Name Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Name Loot Function</em>'.
   * @generated
   */
  SetNameLootFunction createSetNameLootFunction();

  /**
   * Returns a new object of class '<em>Set NBT Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set NBT Loot Function</em>'.
   * @generated
   */
  SetNBTLootFunction createSetNBTLootFunction();

  /**
   * Returns a new object of class '<em>Set Stew Effect Loot Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Stew Effect Loot Function</em>'.
   * @generated
   */
  SetStewEffectLootFunction createSetStewEffectLootFunction();

  /**
   * Returns a new object of class '<em>Stew Effect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stew Effect</em>'.
   * @generated
   */
  StewEffect createStewEffect();

  /**
   * Returns a new object of class '<em>Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loot Condition</em>'.
   * @generated
   */
  LootCondition createLootCondition();

  /**
   * Returns a new object of class '<em>Named Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Named Loot Condition</em>'.
   * @generated
   */
  NamedLootCondition createNamedLootCondition();

  /**
   * Returns a new object of class '<em>Block State Properties Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Block State Properties Loot Condition</em>'.
   * @generated
   */
  BlockStatePropertiesLootCondition createBlockStatePropertiesLootCondition();

  /**
   * Returns a new object of class '<em>Block State Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Block State Property</em>'.
   * @generated
   */
  BlockStateProperty createBlockStateProperty();

  /**
   * Returns a new object of class '<em>Damage Source Properties Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Damage Source Properties Loot Condition</em>'.
   * @generated
   */
  DamageSourcePropertiesLootCondition createDamageSourcePropertiesLootCondition();

  /**
   * Returns a new object of class '<em>Entity Properties Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Properties Loot Condition</em>'.
   * @generated
   */
  EntityPropertiesLootCondition createEntityPropertiesLootCondition();

  /**
   * Returns a new object of class '<em>Entity Scores Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Scores Loot Condition</em>'.
   * @generated
   */
  EntityScoresLootCondition createEntityScoresLootCondition();

  /**
   * Returns a new object of class '<em>Entity Score</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Score</em>'.
   * @generated
   */
  EntityScore createEntityScore();

  /**
   * Returns a new object of class '<em>Killed By Player Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Killed By Player Loot Condition</em>'.
   * @generated
   */
  KilledByPlayerLootCondition createKilledByPlayerLootCondition();

  /**
   * Returns a new object of class '<em>Location Check Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Location Check Loot Condition</em>'.
   * @generated
   */
  LocationCheckLootCondition createLocationCheckLootCondition();

  /**
   * Returns a new object of class '<em>Match Tool Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Match Tool Loot Condition</em>'.
   * @generated
   */
  MatchToolLootCondition createMatchToolLootCondition();

  /**
   * Returns a new object of class '<em>Random Chance Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Random Chance Loot Condition</em>'.
   * @generated
   */
  RandomChanceLootCondition createRandomChanceLootCondition();

  /**
   * Returns a new object of class '<em>Reference Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reference Loot Condition</em>'.
   * @generated
   */
  ReferenceLootCondition createReferenceLootCondition();

  /**
   * Returns a new object of class '<em>Survives Explosion Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Survives Explosion Loot Condition</em>'.
   * @generated
   */
  SurvivesExplosionLootCondition createSurvivesExplosionLootCondition();

  /**
   * Returns a new object of class '<em>Table Bonus Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Bonus Loot Condition</em>'.
   * @generated
   */
  TableBonusLootCondition createTableBonusLootCondition();

  /**
   * Returns a new object of class '<em>Time Check Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time Check Loot Condition</em>'.
   * @generated
   */
  TimeCheckLootCondition createTimeCheckLootCondition();

  /**
   * Returns a new object of class '<em>Tool Enchantment Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tool Enchantment Loot Condition</em>'.
   * @generated
   */
  ToolEnchantmentLootCondition createToolEnchantmentLootCondition();

  /**
   * Returns a new object of class '<em>Enchantment Level</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enchantment Level</em>'.
   * @generated
   */
  EnchantmentLevel createEnchantmentLevel();

  /**
   * Returns a new object of class '<em>Weather Check Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Weather Check Loot Condition</em>'.
   * @generated
   */
  WeatherCheckLootCondition createWeatherCheckLootCondition();

  /**
   * Returns a new object of class '<em>Entity Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Predicate</em>'.
   * @generated
   */
  EntityPredicate createEntityPredicate();

  /**
   * Returns a new object of class '<em>Fishing Hook Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fishing Hook Predicate</em>'.
   * @generated
   */
  FishingHookPredicate createFishingHookPredicate();

  /**
   * Returns a new object of class '<em>Effect Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Predicate</em>'.
   * @generated
   */
  EffectPredicate createEffectPredicate();

  /**
   * Returns a new object of class '<em>Equipment Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equipment Predicate</em>'.
   * @generated
   */
  EquipmentPredicate createEquipmentPredicate();

  /**
   * Returns a new object of class '<em>Entity Flags</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Flags</em>'.
   * @generated
   */
  EntityFlags createEntityFlags();

  /**
   * Returns a new object of class '<em>Player Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Player Predicate</em>'.
   * @generated
   */
  PlayerPredicate createPlayerPredicate();

  /**
   * Returns a new object of class '<em>Advancement Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Advancement Predicate</em>'.
   * @generated
   */
  AdvancementPredicate createAdvancementPredicate();

  /**
   * Returns a new object of class '<em>Advancement Criteria</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Advancement Criteria</em>'.
   * @generated
   */
  AdvancementCriteria createAdvancementCriteria();

  /**
   * Returns a new object of class '<em>Recipe Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Recipe Predicate</em>'.
   * @generated
   */
  RecipePredicate createRecipePredicate();

  /**
   * Returns a new object of class '<em>Statistic Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statistic Predicate</em>'.
   * @generated
   */
  StatisticPredicate createStatisticPredicate();

  /**
   * Returns a new object of class '<em>Single Statistic Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Statistic Predicate</em>'.
   * @generated
   */
  SingleStatisticPredicate createSingleStatisticPredicate();

  /**
   * Returns a new object of class '<em>Namespaced Statistic Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Namespaced Statistic Predicate</em>'.
   * @generated
   */
  NamespacedStatisticPredicate createNamespacedStatisticPredicate();

  /**
   * Returns a new object of class '<em>Unnamespaced Statistic Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unnamespaced Statistic Predicate</em>'.
   * @generated
   */
  UnnamespacedStatisticPredicate createUnnamespacedStatisticPredicate();

  /**
   * Returns a new object of class '<em>Location Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Location Predicate</em>'.
   * @generated
   */
  LocationPredicate createLocationPredicate();

  /**
   * Returns a new object of class '<em>Item Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Item Predicate</em>'.
   * @generated
   */
  ItemPredicate createItemPredicate();

  /**
   * Returns a new object of class '<em>Block Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Block Predicate</em>'.
   * @generated
   */
  BlockPredicate createBlockPredicate();

  /**
   * Returns a new object of class '<em>Block State Property Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Block State Property Predicate</em>'.
   * @generated
   */
  BlockStatePropertyPredicate createBlockStatePropertyPredicate();

  /**
   * Returns a new object of class '<em>Fluid Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fluid Predicate</em>'.
   * @generated
   */
  FluidPredicate createFluidPredicate();

  /**
   * Returns a new object of class '<em>MC Json Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Value</em>'.
   * @generated
   */
  MCJsonValue createMCJsonValue();

  /**
   * Returns a new object of class '<em>MC Json Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Object</em>'.
   * @generated
   */
  MCJsonObject createMCJsonObject();

  /**
   * Returns a new object of class '<em>MC Json Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Entry</em>'.
   * @generated
   */
  MCJsonEntry createMCJsonEntry();

  /**
   * Returns a new object of class '<em>MC Json Array</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Array</em>'.
   * @generated
   */
  MCJsonArray createMCJsonArray();

  /**
   * Returns a new object of class '<em>MC Json String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json String</em>'.
   * @generated
   */
  MCJsonString createMCJsonString();

  /**
   * Returns a new object of class '<em>MC Json Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Number</em>'.
   * @generated
   */
  MCJsonNumber createMCJsonNumber();

  /**
   * Returns a new object of class '<em>MC Json Integral</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Integral</em>'.
   * @generated
   */
  MCJsonIntegral createMCJsonIntegral();

  /**
   * Returns a new object of class '<em>MC Json Floating Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Floating Point</em>'.
   * @generated
   */
  MCJsonFloatingPoint createMCJsonFloatingPoint();

  /**
   * Returns a new object of class '<em>MC Json Boolean</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Boolean</em>'.
   * @generated
   */
  MCJsonBoolean createMCJsonBoolean();

  /**
   * Returns a new object of class '<em>MC Json Null</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MC Json Null</em>'.
   * @generated
   */
  MCJsonNull createMCJsonNull();

  /**
   * Returns a new object of class '<em>Long Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Long Range</em>'.
   * @generated
   */
  LongRange createLongRange();

  /**
   * Returns a new object of class '<em>Exact Long Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exact Long Range</em>'.
   * @generated
   */
  ExactLongRange createExactLongRange();

  /**
   * Returns a new object of class '<em>Normal Long Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Normal Long Range</em>'.
   * @generated
   */
  NormalLongRange createNormalLongRange();

  /**
   * Returns a new object of class '<em>Double Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Double Range</em>'.
   * @generated
   */
  DoubleRange createDoubleRange();

  /**
   * Returns a new object of class '<em>Exact Double Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exact Double Range</em>'.
   * @generated
   */
  ExactDoubleRange createExactDoubleRange();

  /**
   * Returns a new object of class '<em>Normal Double Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Normal Double Range</em>'.
   * @generated
   */
  NormalDoubleRange createNormalDoubleRange();

  /**
   * Returns a new object of class '<em>Loot Function With Conditions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loot Function With Conditions</em>'.
   * @generated
   */
  LootFunctionWithConditions createLootFunctionWithConditions();

  /**
   * Returns a new object of class '<em>Alternative Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alternative Loot Condition</em>'.
   * @generated
   */
  AlternativeLootCondition createAlternativeLootCondition();

  /**
   * Returns a new object of class '<em>Inverted Loot Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inverted Loot Condition</em>'.
   * @generated
   */
  InvertedLootCondition createInvertedLootCondition();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MclootPackage getMclootPackage();

} //MclootFactory
