/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stew Effect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcloottable.mcloot.StewEffect#getType <em>Type</em>}</li>
 *   <li>{@link com.raptor.mcloottable.mcloot.StewEffect#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcloottable.mcloot.MclootPackage#getStewEffect()
 * @model
 * @generated
 */
public interface StewEffect extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see com.raptor.mcloottable.mcloot.MclootPackage#getStewEffect_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link com.raptor.mcloottable.mcloot.StewEffect#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(long)
   * @see com.raptor.mcloottable.mcloot.MclootPackage#getStewEffect_Duration()
   * @model
   * @generated
   */
  long getDuration();

  /**
   * Sets the value of the '{@link com.raptor.mcloottable.mcloot.StewEffect#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(long value);

} // StewEffect
