/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcloottable.mcloot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Weather Check Loot Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcloottable.mcloot.WeatherCheckLootCondition#isInverted <em>Inverted</em>}</li>
 *   <li>{@link com.raptor.mcloottable.mcloot.WeatherCheckLootCondition#isRaining <em>Raining</em>}</li>
 *   <li>{@link com.raptor.mcloottable.mcloot.WeatherCheckLootCondition#isThundering <em>Thundering</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcloottable.mcloot.MclootPackage#getWeatherCheckLootCondition()
 * @model
 * @generated
 */
public interface WeatherCheckLootCondition extends NamedLootCondition
{
  /**
   * Returns the value of the '<em><b>Inverted</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inverted</em>' attribute.
   * @see #setInverted(boolean)
   * @see com.raptor.mcloottable.mcloot.MclootPackage#getWeatherCheckLootCondition_Inverted()
   * @model
   * @generated
   */
  boolean isInverted();

  /**
   * Sets the value of the '{@link com.raptor.mcloottable.mcloot.WeatherCheckLootCondition#isInverted <em>Inverted</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inverted</em>' attribute.
   * @see #isInverted()
   * @generated
   */
  void setInverted(boolean value);

  /**
   * Returns the value of the '<em><b>Raining</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Raining</em>' attribute.
   * @see #setRaining(boolean)
   * @see com.raptor.mcloottable.mcloot.MclootPackage#getWeatherCheckLootCondition_Raining()
   * @model
   * @generated
   */
  boolean isRaining();

  /**
   * Sets the value of the '{@link com.raptor.mcloottable.mcloot.WeatherCheckLootCondition#isRaining <em>Raining</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Raining</em>' attribute.
   * @see #isRaining()
   * @generated
   */
  void setRaining(boolean value);

  /**
   * Returns the value of the '<em><b>Thundering</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thundering</em>' attribute.
   * @see #setThundering(boolean)
   * @see com.raptor.mcloottable.mcloot.MclootPackage#getWeatherCheckLootCondition_Thundering()
   * @model
   * @generated
   */
  boolean isThundering();

  /**
   * Sets the value of the '{@link com.raptor.mcloottable.mcloot.WeatherCheckLootCondition#isThundering <em>Thundering</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thundering</em>' attribute.
   * @see #isThundering()
   * @generated
   */
  void setThundering(boolean value);

} // WeatherCheckLootCondition
