/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcblockstate.mcblockstate;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Base Case Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcblockstate.mcblockstate.BaseCaseCondition#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getBaseCaseCondition()
 * @model
 * @generated
 */
public interface BaseCaseCondition extends CaseCondition
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.raptor.mcblockstate.mcblockstate.BlockstatePropertyPredicate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getBaseCaseCondition_Properties()
   * @model containment="true"
   * @generated
   */
  EList<BlockstatePropertyPredicate> getProperties();

} // BaseCaseCondition
