/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcblockstate.mcblockstate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Blockstate Property Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcblockstate.mcblockstate.BooleanBlockstatePropertyPredicate#isInverted <em>Inverted</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getBooleanBlockstatePropertyPredicate()
 * @model
 * @generated
 */
public interface BooleanBlockstatePropertyPredicate extends BlockstatePropertyPredicate
{
  /**
   * Returns the value of the '<em><b>Inverted</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inverted</em>' attribute.
   * @see #setInverted(boolean)
   * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getBooleanBlockstatePropertyPredicate_Inverted()
   * @model
   * @generated
   */
  boolean isInverted();

  /**
   * Sets the value of the '{@link com.raptor.mcblockstate.mcblockstate.BooleanBlockstatePropertyPredicate#isInverted <em>Inverted</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inverted</em>' attribute.
   * @see #isInverted()
   * @generated
   */
  void setInverted(boolean value);

} // BooleanBlockstatePropertyPredicate
