/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcblockstate.mcblockstate;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.raptor.mcblockstate.mcblockstate.McblockstateFactory
 * @model kind="package"
 * @generated
 */
public interface McblockstatePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mcblockstate";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.raptor.com/mcblockstate/Mcblockstate";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mcblockstate";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  McblockstatePackage eINSTANCE = com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl.init();

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BlockstateImpl <em>Blockstate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.BlockstateImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBlockstate()
   * @generated
   */
  int BLOCKSTATE = 0;

  /**
   * The number of structural features of the '<em>Blockstate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCKSTATE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.VariantsBlockstateImpl <em>Variants Blockstate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.VariantsBlockstateImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getVariantsBlockstate()
   * @generated
   */
  int VARIANTS_BLOCKSTATE = 1;

  /**
   * The feature id for the '<em><b>Variants</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANTS_BLOCKSTATE__VARIANTS = BLOCKSTATE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variants Blockstate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANTS_BLOCKSTATE_FEATURE_COUNT = BLOCKSTATE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.VariantImpl <em>Variant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.VariantImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getVariant()
   * @generated
   */
  int VARIANT = 2;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANT__PROPERTIES = 0;

  /**
   * The feature id for the '<em><b>Models</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANT__MODELS = 1;

  /**
   * The number of structural features of the '<em>Variant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BlockstatePropertyImpl <em>Blockstate Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.BlockstatePropertyImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBlockstateProperty()
   * @generated
   */
  int BLOCKSTATE_PROPERTY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCKSTATE_PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCKSTATE_PROPERTY__VALUE = 1;

  /**
   * The number of structural features of the '<em>Blockstate Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCKSTATE_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MultipartBlockstateImpl <em>Multipart Blockstate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MultipartBlockstateImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMultipartBlockstate()
   * @generated
   */
  int MULTIPART_BLOCKSTATE = 4;

  /**
   * The feature id for the '<em><b>Cases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPART_BLOCKSTATE__CASES = BLOCKSTATE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Multipart Blockstate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPART_BLOCKSTATE_FEATURE_COUNT = BLOCKSTATE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.CaseImpl <em>Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.CaseImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getCase()
   * @generated
   */
  int CASE = 5;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Models</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE__MODELS = 1;

  /**
   * The number of structural features of the '<em>Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.CaseConditionImpl <em>Case Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.CaseConditionImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getCaseCondition()
   * @generated
   */
  int CASE_CONDITION = 6;

  /**
   * The number of structural features of the '<em>Case Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_CONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BlockstatePropertyPredicateImpl <em>Blockstate Property Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.BlockstatePropertyPredicateImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBlockstatePropertyPredicate()
   * @generated
   */
  int BLOCKSTATE_PROPERTY_PREDICATE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCKSTATE_PROPERTY_PREDICATE__NAME = 0;

  /**
   * The number of structural features of the '<em>Blockstate Property Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCKSTATE_PROPERTY_PREDICATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.CustomBlockstateImpl <em>Custom Blockstate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.CustomBlockstateImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getCustomBlockstate()
   * @generated
   */
  int CUSTOM_BLOCKSTATE = 8;

  /**
   * The feature id for the '<em><b>Json</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_BLOCKSTATE__JSON = BLOCKSTATE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Custom Blockstate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_BLOCKSTATE_FEATURE_COUNT = BLOCKSTATE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.ModelListImpl <em>Model List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.ModelListImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getModelList()
   * @generated
   */
  int MODEL_LIST = 9;

  /**
   * The feature id for the '<em><b>Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_LIST__MODELS = 0;

  /**
   * The number of structural features of the '<em>Model List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.ModelImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getModel()
   * @generated
   */
  int MODEL = 10;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__LOCATION = 0;

  /**
   * The feature id for the '<em><b>Weight Defined</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WEIGHT_DEFINED = 1;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WEIGHT = 2;

  /**
   * The feature id for the '<em><b>XDefined</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__XDEFINED = 3;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__X = 4;

  /**
   * The feature id for the '<em><b>YDefined</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__YDEFINED = 5;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__Y = 6;

  /**
   * The feature id for the '<em><b>Uvlock Defined</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__UVLOCK_DEFINED = 7;

  /**
   * The feature id for the '<em><b>Uvlock</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__UVLOCK = 8;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonValueImpl <em>MC Json Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonValueImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonValue()
   * @generated
   */
  int MC_JSON_VALUE = 11;

  /**
   * The number of structural features of the '<em>MC Json Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonObjectImpl <em>MC Json Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonObjectImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonObject()
   * @generated
   */
  int MC_JSON_OBJECT = 12;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_OBJECT__ENTRIES = MC_JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MC Json Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_OBJECT_FEATURE_COUNT = MC_JSON_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonEntryImpl <em>MC Json Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonEntryImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonEntry()
   * @generated
   */
  int MC_JSON_ENTRY = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_ENTRY__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_ENTRY__VALUE = 1;

  /**
   * The number of structural features of the '<em>MC Json Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_ENTRY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonArrayImpl <em>MC Json Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonArrayImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonArray()
   * @generated
   */
  int MC_JSON_ARRAY = 14;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_ARRAY__ELEMENTS = MC_JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MC Json Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_ARRAY_FEATURE_COUNT = MC_JSON_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonStringImpl <em>MC Json String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonStringImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonString()
   * @generated
   */
  int MC_JSON_STRING = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_STRING__VALUE = MC_JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MC Json String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_STRING_FEATURE_COUNT = MC_JSON_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonNumberImpl <em>MC Json Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonNumberImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonNumber()
   * @generated
   */
  int MC_JSON_NUMBER = 16;

  /**
   * The number of structural features of the '<em>MC Json Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_NUMBER_FEATURE_COUNT = MC_JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonIntegralImpl <em>MC Json Integral</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonIntegralImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonIntegral()
   * @generated
   */
  int MC_JSON_INTEGRAL = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_INTEGRAL__VALUE = MC_JSON_NUMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MC Json Integral</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_INTEGRAL_FEATURE_COUNT = MC_JSON_NUMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonFloatingPointImpl <em>MC Json Floating Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonFloatingPointImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonFloatingPoint()
   * @generated
   */
  int MC_JSON_FLOATING_POINT = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_FLOATING_POINT__VALUE = MC_JSON_NUMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MC Json Floating Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_FLOATING_POINT_FEATURE_COUNT = MC_JSON_NUMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonBooleanImpl <em>MC Json Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonBooleanImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonBoolean()
   * @generated
   */
  int MC_JSON_BOOLEAN = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_BOOLEAN__VALUE = MC_JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MC Json Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_BOOLEAN_FEATURE_COUNT = MC_JSON_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonNullImpl <em>MC Json Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonNullImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonNull()
   * @generated
   */
  int MC_JSON_NULL = 20;

  /**
   * The number of structural features of the '<em>MC Json Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_JSON_NULL_FEATURE_COUNT = MC_JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.OrCaseConditionImpl <em>Or Case Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.OrCaseConditionImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getOrCaseCondition()
   * @generated
   */
  int OR_CASE_CONDITION = 21;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CASE_CONDITION__OPTIONS = CASE_CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Or Case Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CASE_CONDITION_FEATURE_COUNT = CASE_CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BaseCaseConditionImpl <em>Base Case Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.BaseCaseConditionImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBaseCaseCondition()
   * @generated
   */
  int BASE_CASE_CONDITION = 22;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_CASE_CONDITION__PROPERTIES = CASE_CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Base Case Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_CASE_CONDITION_FEATURE_COUNT = CASE_CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.NormalBlockstatePropertyPredicateImpl <em>Normal Blockstate Property Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.NormalBlockstatePropertyPredicateImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getNormalBlockstatePropertyPredicate()
   * @generated
   */
  int NORMAL_BLOCKSTATE_PROPERTY_PREDICATE = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_BLOCKSTATE_PROPERTY_PREDICATE__NAME = BLOCKSTATE_PROPERTY_PREDICATE__NAME;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_BLOCKSTATE_PROPERTY_PREDICATE__VALUES = BLOCKSTATE_PROPERTY_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Normal Blockstate Property Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_BLOCKSTATE_PROPERTY_PREDICATE_FEATURE_COUNT = BLOCKSTATE_PROPERTY_PREDICATE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BooleanBlockstatePropertyPredicateImpl <em>Boolean Blockstate Property Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.raptor.mcblockstate.mcblockstate.impl.BooleanBlockstatePropertyPredicateImpl
   * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBooleanBlockstatePropertyPredicate()
   * @generated
   */
  int BOOLEAN_BLOCKSTATE_PROPERTY_PREDICATE = 24;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_BLOCKSTATE_PROPERTY_PREDICATE__NAME = BLOCKSTATE_PROPERTY_PREDICATE__NAME;

  /**
   * The feature id for the '<em><b>Inverted</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_BLOCKSTATE_PROPERTY_PREDICATE__INVERTED = BLOCKSTATE_PROPERTY_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Blockstate Property Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_BLOCKSTATE_PROPERTY_PREDICATE_FEATURE_COUNT = BLOCKSTATE_PROPERTY_PREDICATE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.Blockstate <em>Blockstate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Blockstate</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Blockstate
   * @generated
   */
  EClass getBlockstate();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.VariantsBlockstate <em>Variants Blockstate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variants Blockstate</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.VariantsBlockstate
   * @generated
   */
  EClass getVariantsBlockstate();

  /**
   * Returns the meta object for the containment reference list '{@link com.raptor.mcblockstate.mcblockstate.VariantsBlockstate#getVariants <em>Variants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variants</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.VariantsBlockstate#getVariants()
   * @see #getVariantsBlockstate()
   * @generated
   */
  EReference getVariantsBlockstate_Variants();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.Variant <em>Variant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variant</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Variant
   * @generated
   */
  EClass getVariant();

  /**
   * Returns the meta object for the containment reference list '{@link com.raptor.mcblockstate.mcblockstate.Variant#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Variant#getProperties()
   * @see #getVariant()
   * @generated
   */
  EReference getVariant_Properties();

  /**
   * Returns the meta object for the containment reference '{@link com.raptor.mcblockstate.mcblockstate.Variant#getModels <em>Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Models</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Variant#getModels()
   * @see #getVariant()
   * @generated
   */
  EReference getVariant_Models();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.BlockstateProperty <em>Blockstate Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Blockstate Property</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BlockstateProperty
   * @generated
   */
  EClass getBlockstateProperty();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.BlockstateProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BlockstateProperty#getName()
   * @see #getBlockstateProperty()
   * @generated
   */
  EAttribute getBlockstateProperty_Name();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.BlockstateProperty#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BlockstateProperty#getValue()
   * @see #getBlockstateProperty()
   * @generated
   */
  EAttribute getBlockstateProperty_Value();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MultipartBlockstate <em>Multipart Blockstate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multipart Blockstate</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MultipartBlockstate
   * @generated
   */
  EClass getMultipartBlockstate();

  /**
   * Returns the meta object for the containment reference list '{@link com.raptor.mcblockstate.mcblockstate.MultipartBlockstate#getCases <em>Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cases</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MultipartBlockstate#getCases()
   * @see #getMultipartBlockstate()
   * @generated
   */
  EReference getMultipartBlockstate_Cases();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.Case <em>Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Case</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Case
   * @generated
   */
  EClass getCase();

  /**
   * Returns the meta object for the containment reference '{@link com.raptor.mcblockstate.mcblockstate.Case#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Case#getCondition()
   * @see #getCase()
   * @generated
   */
  EReference getCase_Condition();

  /**
   * Returns the meta object for the containment reference '{@link com.raptor.mcblockstate.mcblockstate.Case#getModels <em>Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Models</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Case#getModels()
   * @see #getCase()
   * @generated
   */
  EReference getCase_Models();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.CaseCondition <em>Case Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Case Condition</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.CaseCondition
   * @generated
   */
  EClass getCaseCondition();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.BlockstatePropertyPredicate <em>Blockstate Property Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Blockstate Property Predicate</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BlockstatePropertyPredicate
   * @generated
   */
  EClass getBlockstatePropertyPredicate();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.BlockstatePropertyPredicate#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BlockstatePropertyPredicate#getName()
   * @see #getBlockstatePropertyPredicate()
   * @generated
   */
  EAttribute getBlockstatePropertyPredicate_Name();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.CustomBlockstate <em>Custom Blockstate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Custom Blockstate</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.CustomBlockstate
   * @generated
   */
  EClass getCustomBlockstate();

  /**
   * Returns the meta object for the containment reference '{@link com.raptor.mcblockstate.mcblockstate.CustomBlockstate#getJson <em>Json</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Json</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.CustomBlockstate#getJson()
   * @see #getCustomBlockstate()
   * @generated
   */
  EReference getCustomBlockstate_Json();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.ModelList <em>Model List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model List</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.ModelList
   * @generated
   */
  EClass getModelList();

  /**
   * Returns the meta object for the containment reference list '{@link com.raptor.mcblockstate.mcblockstate.ModelList#getModels <em>Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Models</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.ModelList#getModels()
   * @see #getModelList()
   * @generated
   */
  EReference getModelList_Models();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#getLocation()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Location();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#isWeightDefined <em>Weight Defined</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight Defined</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#isWeightDefined()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_WeightDefined();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#getWeight()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Weight();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#isXDefined <em>XDefined</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>XDefined</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#isXDefined()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_XDefined();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#getX()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_X();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#isYDefined <em>YDefined</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>YDefined</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#isYDefined()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_YDefined();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#getY()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Y();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#isUvlockDefined <em>Uvlock Defined</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uvlock Defined</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#isUvlockDefined()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_UvlockDefined();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.Model#isUvlock <em>Uvlock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uvlock</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.Model#isUvlock()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Uvlock();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonValue <em>MC Json Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Value</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonValue
   * @generated
   */
  EClass getMCJsonValue();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonObject <em>MC Json Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Object</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonObject
   * @generated
   */
  EClass getMCJsonObject();

  /**
   * Returns the meta object for the containment reference list '{@link com.raptor.mcblockstate.mcblockstate.MCJsonObject#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonObject#getEntries()
   * @see #getMCJsonObject()
   * @generated
   */
  EReference getMCJsonObject_Entries();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonEntry <em>MC Json Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Entry</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonEntry
   * @generated
   */
  EClass getMCJsonEntry();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.MCJsonEntry#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonEntry#getName()
   * @see #getMCJsonEntry()
   * @generated
   */
  EAttribute getMCJsonEntry_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.raptor.mcblockstate.mcblockstate.MCJsonEntry#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonEntry#getValue()
   * @see #getMCJsonEntry()
   * @generated
   */
  EReference getMCJsonEntry_Value();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonArray <em>MC Json Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Array</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonArray
   * @generated
   */
  EClass getMCJsonArray();

  /**
   * Returns the meta object for the containment reference list '{@link com.raptor.mcblockstate.mcblockstate.MCJsonArray#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonArray#getElements()
   * @see #getMCJsonArray()
   * @generated
   */
  EReference getMCJsonArray_Elements();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonString <em>MC Json String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json String</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonString
   * @generated
   */
  EClass getMCJsonString();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.MCJsonString#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonString#getValue()
   * @see #getMCJsonString()
   * @generated
   */
  EAttribute getMCJsonString_Value();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonNumber <em>MC Json Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Number</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonNumber
   * @generated
   */
  EClass getMCJsonNumber();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonIntegral <em>MC Json Integral</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Integral</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonIntegral
   * @generated
   */
  EClass getMCJsonIntegral();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.MCJsonIntegral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonIntegral#getValue()
   * @see #getMCJsonIntegral()
   * @generated
   */
  EAttribute getMCJsonIntegral_Value();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonFloatingPoint <em>MC Json Floating Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Floating Point</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonFloatingPoint
   * @generated
   */
  EClass getMCJsonFloatingPoint();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.MCJsonFloatingPoint#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonFloatingPoint#getValue()
   * @see #getMCJsonFloatingPoint()
   * @generated
   */
  EAttribute getMCJsonFloatingPoint_Value();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonBoolean <em>MC Json Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Boolean</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonBoolean
   * @generated
   */
  EClass getMCJsonBoolean();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.MCJsonBoolean#isValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonBoolean#isValue()
   * @see #getMCJsonBoolean()
   * @generated
   */
  EAttribute getMCJsonBoolean_Value();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.MCJsonNull <em>MC Json Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Json Null</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.MCJsonNull
   * @generated
   */
  EClass getMCJsonNull();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.OrCaseCondition <em>Or Case Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Case Condition</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.OrCaseCondition
   * @generated
   */
  EClass getOrCaseCondition();

  /**
   * Returns the meta object for the containment reference list '{@link com.raptor.mcblockstate.mcblockstate.OrCaseCondition#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.OrCaseCondition#getOptions()
   * @see #getOrCaseCondition()
   * @generated
   */
  EReference getOrCaseCondition_Options();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.BaseCaseCondition <em>Base Case Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base Case Condition</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BaseCaseCondition
   * @generated
   */
  EClass getBaseCaseCondition();

  /**
   * Returns the meta object for the containment reference list '{@link com.raptor.mcblockstate.mcblockstate.BaseCaseCondition#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BaseCaseCondition#getProperties()
   * @see #getBaseCaseCondition()
   * @generated
   */
  EReference getBaseCaseCondition_Properties();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.NormalBlockstatePropertyPredicate <em>Normal Blockstate Property Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normal Blockstate Property Predicate</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.NormalBlockstatePropertyPredicate
   * @generated
   */
  EClass getNormalBlockstatePropertyPredicate();

  /**
   * Returns the meta object for the attribute list '{@link com.raptor.mcblockstate.mcblockstate.NormalBlockstatePropertyPredicate#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.NormalBlockstatePropertyPredicate#getValues()
   * @see #getNormalBlockstatePropertyPredicate()
   * @generated
   */
  EAttribute getNormalBlockstatePropertyPredicate_Values();

  /**
   * Returns the meta object for class '{@link com.raptor.mcblockstate.mcblockstate.BooleanBlockstatePropertyPredicate <em>Boolean Blockstate Property Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Blockstate Property Predicate</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BooleanBlockstatePropertyPredicate
   * @generated
   */
  EClass getBooleanBlockstatePropertyPredicate();

  /**
   * Returns the meta object for the attribute '{@link com.raptor.mcblockstate.mcblockstate.BooleanBlockstatePropertyPredicate#isInverted <em>Inverted</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Inverted</em>'.
   * @see com.raptor.mcblockstate.mcblockstate.BooleanBlockstatePropertyPredicate#isInverted()
   * @see #getBooleanBlockstatePropertyPredicate()
   * @generated
   */
  EAttribute getBooleanBlockstatePropertyPredicate_Inverted();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  McblockstateFactory getMcblockstateFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BlockstateImpl <em>Blockstate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.BlockstateImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBlockstate()
     * @generated
     */
    EClass BLOCKSTATE = eINSTANCE.getBlockstate();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.VariantsBlockstateImpl <em>Variants Blockstate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.VariantsBlockstateImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getVariantsBlockstate()
     * @generated
     */
    EClass VARIANTS_BLOCKSTATE = eINSTANCE.getVariantsBlockstate();

    /**
     * The meta object literal for the '<em><b>Variants</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIANTS_BLOCKSTATE__VARIANTS = eINSTANCE.getVariantsBlockstate_Variants();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.VariantImpl <em>Variant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.VariantImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getVariant()
     * @generated
     */
    EClass VARIANT = eINSTANCE.getVariant();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIANT__PROPERTIES = eINSTANCE.getVariant_Properties();

    /**
     * The meta object literal for the '<em><b>Models</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIANT__MODELS = eINSTANCE.getVariant_Models();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BlockstatePropertyImpl <em>Blockstate Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.BlockstatePropertyImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBlockstateProperty()
     * @generated
     */
    EClass BLOCKSTATE_PROPERTY = eINSTANCE.getBlockstateProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCKSTATE_PROPERTY__NAME = eINSTANCE.getBlockstateProperty_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCKSTATE_PROPERTY__VALUE = eINSTANCE.getBlockstateProperty_Value();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MultipartBlockstateImpl <em>Multipart Blockstate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MultipartBlockstateImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMultipartBlockstate()
     * @generated
     */
    EClass MULTIPART_BLOCKSTATE = eINSTANCE.getMultipartBlockstate();

    /**
     * The meta object literal for the '<em><b>Cases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPART_BLOCKSTATE__CASES = eINSTANCE.getMultipartBlockstate_Cases();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.CaseImpl <em>Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.CaseImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getCase()
     * @generated
     */
    EClass CASE = eINSTANCE.getCase();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE__CONDITION = eINSTANCE.getCase_Condition();

    /**
     * The meta object literal for the '<em><b>Models</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE__MODELS = eINSTANCE.getCase_Models();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.CaseConditionImpl <em>Case Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.CaseConditionImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getCaseCondition()
     * @generated
     */
    EClass CASE_CONDITION = eINSTANCE.getCaseCondition();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BlockstatePropertyPredicateImpl <em>Blockstate Property Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.BlockstatePropertyPredicateImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBlockstatePropertyPredicate()
     * @generated
     */
    EClass BLOCKSTATE_PROPERTY_PREDICATE = eINSTANCE.getBlockstatePropertyPredicate();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCKSTATE_PROPERTY_PREDICATE__NAME = eINSTANCE.getBlockstatePropertyPredicate_Name();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.CustomBlockstateImpl <em>Custom Blockstate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.CustomBlockstateImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getCustomBlockstate()
     * @generated
     */
    EClass CUSTOM_BLOCKSTATE = eINSTANCE.getCustomBlockstate();

    /**
     * The meta object literal for the '<em><b>Json</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOM_BLOCKSTATE__JSON = eINSTANCE.getCustomBlockstate_Json();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.ModelListImpl <em>Model List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.ModelListImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getModelList()
     * @generated
     */
    EClass MODEL_LIST = eINSTANCE.getModelList();

    /**
     * The meta object literal for the '<em><b>Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL_LIST__MODELS = eINSTANCE.getModelList_Models();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.ModelImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__LOCATION = eINSTANCE.getModel_Location();

    /**
     * The meta object literal for the '<em><b>Weight Defined</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__WEIGHT_DEFINED = eINSTANCE.getModel_WeightDefined();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__WEIGHT = eINSTANCE.getModel_Weight();

    /**
     * The meta object literal for the '<em><b>XDefined</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__XDEFINED = eINSTANCE.getModel_XDefined();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__X = eINSTANCE.getModel_X();

    /**
     * The meta object literal for the '<em><b>YDefined</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__YDEFINED = eINSTANCE.getModel_YDefined();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__Y = eINSTANCE.getModel_Y();

    /**
     * The meta object literal for the '<em><b>Uvlock Defined</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__UVLOCK_DEFINED = eINSTANCE.getModel_UvlockDefined();

    /**
     * The meta object literal for the '<em><b>Uvlock</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__UVLOCK = eINSTANCE.getModel_Uvlock();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonValueImpl <em>MC Json Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonValueImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonValue()
     * @generated
     */
    EClass MC_JSON_VALUE = eINSTANCE.getMCJsonValue();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonObjectImpl <em>MC Json Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonObjectImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonObject()
     * @generated
     */
    EClass MC_JSON_OBJECT = eINSTANCE.getMCJsonObject();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MC_JSON_OBJECT__ENTRIES = eINSTANCE.getMCJsonObject_Entries();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonEntryImpl <em>MC Json Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonEntryImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonEntry()
     * @generated
     */
    EClass MC_JSON_ENTRY = eINSTANCE.getMCJsonEntry();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MC_JSON_ENTRY__NAME = eINSTANCE.getMCJsonEntry_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MC_JSON_ENTRY__VALUE = eINSTANCE.getMCJsonEntry_Value();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonArrayImpl <em>MC Json Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonArrayImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonArray()
     * @generated
     */
    EClass MC_JSON_ARRAY = eINSTANCE.getMCJsonArray();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MC_JSON_ARRAY__ELEMENTS = eINSTANCE.getMCJsonArray_Elements();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonStringImpl <em>MC Json String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonStringImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonString()
     * @generated
     */
    EClass MC_JSON_STRING = eINSTANCE.getMCJsonString();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MC_JSON_STRING__VALUE = eINSTANCE.getMCJsonString_Value();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonNumberImpl <em>MC Json Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonNumberImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonNumber()
     * @generated
     */
    EClass MC_JSON_NUMBER = eINSTANCE.getMCJsonNumber();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonIntegralImpl <em>MC Json Integral</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonIntegralImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonIntegral()
     * @generated
     */
    EClass MC_JSON_INTEGRAL = eINSTANCE.getMCJsonIntegral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MC_JSON_INTEGRAL__VALUE = eINSTANCE.getMCJsonIntegral_Value();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonFloatingPointImpl <em>MC Json Floating Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonFloatingPointImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonFloatingPoint()
     * @generated
     */
    EClass MC_JSON_FLOATING_POINT = eINSTANCE.getMCJsonFloatingPoint();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MC_JSON_FLOATING_POINT__VALUE = eINSTANCE.getMCJsonFloatingPoint_Value();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonBooleanImpl <em>MC Json Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonBooleanImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonBoolean()
     * @generated
     */
    EClass MC_JSON_BOOLEAN = eINSTANCE.getMCJsonBoolean();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MC_JSON_BOOLEAN__VALUE = eINSTANCE.getMCJsonBoolean_Value();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.MCJsonNullImpl <em>MC Json Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.MCJsonNullImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getMCJsonNull()
     * @generated
     */
    EClass MC_JSON_NULL = eINSTANCE.getMCJsonNull();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.OrCaseConditionImpl <em>Or Case Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.OrCaseConditionImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getOrCaseCondition()
     * @generated
     */
    EClass OR_CASE_CONDITION = eINSTANCE.getOrCaseCondition();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_CASE_CONDITION__OPTIONS = eINSTANCE.getOrCaseCondition_Options();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BaseCaseConditionImpl <em>Base Case Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.BaseCaseConditionImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBaseCaseCondition()
     * @generated
     */
    EClass BASE_CASE_CONDITION = eINSTANCE.getBaseCaseCondition();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BASE_CASE_CONDITION__PROPERTIES = eINSTANCE.getBaseCaseCondition_Properties();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.NormalBlockstatePropertyPredicateImpl <em>Normal Blockstate Property Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.NormalBlockstatePropertyPredicateImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getNormalBlockstatePropertyPredicate()
     * @generated
     */
    EClass NORMAL_BLOCKSTATE_PROPERTY_PREDICATE = eINSTANCE.getNormalBlockstatePropertyPredicate();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NORMAL_BLOCKSTATE_PROPERTY_PREDICATE__VALUES = eINSTANCE.getNormalBlockstatePropertyPredicate_Values();

    /**
     * The meta object literal for the '{@link com.raptor.mcblockstate.mcblockstate.impl.BooleanBlockstatePropertyPredicateImpl <em>Boolean Blockstate Property Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.raptor.mcblockstate.mcblockstate.impl.BooleanBlockstatePropertyPredicateImpl
     * @see com.raptor.mcblockstate.mcblockstate.impl.McblockstatePackageImpl#getBooleanBlockstatePropertyPredicate()
     * @generated
     */
    EClass BOOLEAN_BLOCKSTATE_PROPERTY_PREDICATE = eINSTANCE.getBooleanBlockstatePropertyPredicate();

    /**
     * The meta object literal for the '<em><b>Inverted</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_BLOCKSTATE_PROPERTY_PREDICATE__INVERTED = eINSTANCE.getBooleanBlockstatePropertyPredicate_Inverted();

  }

} //McblockstatePackage
