/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcblockstate.mcblockstate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MC Json String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcblockstate.mcblockstate.MCJsonString#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getMCJsonString()
 * @model
 * @generated
 */
public interface MCJsonString extends MCJsonValue
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getMCJsonString_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link com.raptor.mcblockstate.mcblockstate.MCJsonString#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // MCJsonString
