/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcblockstate.mcblockstate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcblockstate.mcblockstate.Variant#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.raptor.mcblockstate.mcblockstate.Variant#getModels <em>Models</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getVariant()
 * @model
 * @generated
 */
public interface Variant extends EObject
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.raptor.mcblockstate.mcblockstate.BlockstateProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getVariant_Properties()
   * @model containment="true"
   * @generated
   */
  EList<BlockstateProperty> getProperties();

  /**
   * Returns the value of the '<em><b>Models</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Models</em>' containment reference.
   * @see #setModels(ModelList)
   * @see com.raptor.mcblockstate.mcblockstate.McblockstatePackage#getVariant_Models()
   * @model containment="true"
   * @generated
   */
  ModelList getModels();

  /**
   * Sets the value of the '{@link com.raptor.mcblockstate.mcblockstate.Variant#getModels <em>Models</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Models</em>' containment reference.
   * @see #getModels()
   * @generated
   */
  void setModels(ModelList value);

} // Variant
