/**
 * generated by Xtext 2.21.0
 */
package com.raptor.mcmodel.ui;

import com.raptor.mcmodel.ui.AbstractMcmodelUiModule;
import com.raptor.mcmodel.ui.editor.syntaxcoloring.McmodelAntlrTokenToAttributeIdMapper;
import com.raptor.mcmodel.ui.editor.syntaxcoloring.McmodelHighlightingConfiguration;
import com.raptor.mcmodel.ui.editor.syntaxcoloring.McmodelSemanticHighlightingCalculator;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class McmodelUiModule extends AbstractMcmodelUiModule {
  public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
    return McmodelAntlrTokenToAttributeIdMapper.class;
  }
  
  public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
    return McmodelSemanticHighlightingCalculator.class;
  }
  
  public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
    return McmodelHighlightingConfiguration.class;
  }
  
  public McmodelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
