/*
 * generated by Xtext 2.21.0
 */
package com.raptor.mcblockstate.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMcblockstateValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.raptor.mcblockstate.mcblockstate.McblockstatePackage.eINSTANCE);
		return result;
	}
}
