/*
 * generated by Xtext 2.21.0
 */
package com.raptor.mcblockstate.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class McblockstateAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/raptor/mcblockstate/parser/antlr/internal/InternalMcblockstate.tokens");
	}
}
