/**
 * generated by Xtext 2.19.0
 */
package com.raptor.mcentity.mcentity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcentity.mcentity.EntityData#getNbt <em>Nbt</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcentity.mcentity.McentityPackage#getEntityData()
 * @model
 * @generated
 */
public interface EntityData extends EObject
{
  /**
   * Returns the value of the '<em><b>Nbt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbt</em>' containment reference.
   * @see #setNbt(NBTCompound)
   * @see com.raptor.mcentity.mcentity.McentityPackage#getEntityData_Nbt()
   * @model containment="true"
   * @generated
   */
  NBTCompound getNbt();

  /**
   * Sets the value of the '{@link com.raptor.mcentity.mcentity.EntityData#getNbt <em>Nbt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbt</em>' containment reference.
   * @see #getNbt()
   * @generated
   */
  void setNbt(NBTCompound value);

} // EntityData
