/**
 * generated by Xtext 2.19.0
 */
package com.raptor.mcentity.mcentity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NBT Float</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.raptor.mcentity.mcentity.NBTFloat#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.raptor.mcentity.mcentity.McentityPackage#getNBTFloat()
 * @model
 * @generated
 */
public interface NBTFloat extends NBTNumber
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(float)
   * @see com.raptor.mcentity.mcentity.McentityPackage#getNBTFloat_Value()
   * @model
   * @generated
   */
  float getValue();

  /**
   * Sets the value of the '{@link com.raptor.mcentity.mcentity.NBTFloat#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(float value);

} // NBTFloat
