/**
 * generated by Xtext 2.19.0
 */
package com.raptor.mcentity.mcentity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NBT Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.raptor.mcentity.mcentity.McentityPackage#getNBTNumber()
 * @model
 * @generated
 */
public interface NBTNumber extends NBTValue
{
} // NBTNumber
